### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by ChekinNooget** [epiccakeking/aops-enhanced#28]
**more forums on user page**
can you make it so that you can see all of the forums you've posted in on your user profile? right now you can only see your top eight which is kind of annoying...

https://artofproblemsolving.com/community/user/501245

i have no idea where most of my post count is coming from so i think this would be useful

**8char limit**
if you are below the 8char limit, then it automatically adds $       $ at the end of the post for you.

**custom forum color**
only visible to you, but you can select a forum and have it's header change color. useful to differentiate between all the different forums you post in

**auto sort feed**
usually you have to click the button after you post to sort your feed, but this will automatically do it for u

**user tagging**
if you type someone's username in a message, it automatically links to their profile. for example if you click @aayr then it would link to my profile page

**alcumus sidebar**
remove the annoying "ready for the next challenge?" in the alcumus page https://artofproblemsolving.com/alcumus

**Comment by epiccakeking** [comment]
Adding more forums would require making a massive number of requests, and in general not be feasible unless there is a hidden endpoint (in which case there is the question of whether this should be considered exposing data that isn't intended to be exposed, which I am against including).

For the ones regarding post formatting (8char and @ links), I'm also somewhat against these since they generally act in an obtuse manner; either they insert code while editing that interrupts the flow of writing, or they act to change the contents of messages before they are sent, which makes it possible for your post to become formatted in a way that you don't intend. At most I think there could be a custom toolbar button for inserting such things.

Forum colors would be doable, but would be somewhat ugly to implement as it would need a new UI element for managing colors.

Resorting feed would actually be a decent option to have

For the alcumus sidebar it would probably be much better suited left off to being done in an actual content blocker.

If you would like to elaborate on your proposals, feel free to open new issues for them (please use one issue per proposal, it makes it easier to manage)

**Comment by ChekinNooget** [comment]
ok, thank you
